import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="navigation">
          <div className="w-full h-32 bg-gray-500 "></div>
        </header>

        <div className="flex flex-col md:flex-row justify-around items-center md:items-start mt-[5%]">
          {children}
          <div className="w-60 h-96 bg-gray-400"></div>
        </div>

        <footer className=" bg-gray-700 text-white p-10 mt-16">
          <div className="flex flex-col md:flex-row justify-around gap-16 mb-3">
            <div className=""> Trending Fintech Ecommerce Telecom Startup</div>
            <div className="">Public Relations Advertise with us</div>
            <div className="">About About Us Our Team Contact Us</div>
            <div className="">Legal Privacy Policy Terms of Service Disclosure</div>
            <div className=""> Connect to us on:</div>
          </div>
          Copyright © 2024 Shega Media & Technology PLC</footer>
      </body>
    </html>
  );
}
